DROP TABLE IF EXISTS  transactions;

CREATE TABLE transactions(
id INT UNSIGNED AUTO_INCREMENT  PRIMARY KEY NOT NULL,
user_id  INT UNSIGNED NULL,
product_id INT UNSIGNED NULL,
create_time TIMESTAMP not null,
FOREIGN KEY (user_id) REFERENCES  users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE  ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;